Ols stats modification
CesarCaballeroGaudes/tedana pull request #3
Opened 2019-12-02 11:30 UTC by smoia

Closes # .

Changes proposed in this pull request:

- removed unused parameter from computefeats2
-

2019-12-03 10:36 UTC, smoia commented
The only thing we have to pay attention to is when `computefeats2` gets called by `kundu_fit`:
- in `upstream` the Fisher's Z scores aren't scaled by their standard deviation, where otherwise they are;
- in this code, we never scale by the standard deviation - probably due to the fact that it's properly computed Z values for statistical test?

2019-12-11 22:04 UTC, CesarCaballeroGaudes requested changes

2019-12-11 22:04 UTC, CesarCaballeroGaudes commented on tedana/stats.py
> +    betas = np.nan_to_num(betas, posinf=30, neginf=-30)
I understand the limit to the z_values, but why are you establishing a limit to the betas?

2019-12-11 23:45 UTC, CesarCaballeroGaudes approved these changes

2019-12-11 23:45 UTC, merged